name: Run Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Set up SSH key
      run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_private_key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      id: ssh-key

    - name: Set up SSH agent
      run: |
        eval "$(ssh-agent -s)"
        chmod 600 ssh_private_key
        ssh-add ssh_private_key

    - name: Run Ansible Playbook
      run: |
        ansible-playbook -i inventory.ini massive.yaml --private-key=ssh_private_key -vv