name: Run Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Run Ansible Playbook
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        ls -la
        ansible-playbook -i inventory.ini massive.yaml -vv