name: Run Ansible Playbook

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Set up SSH key
      run: |
        mkdir .ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > id_rsa
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      id: ssh-key

    - name: Set up SSH agent
      run: |
        eval "$(ssh-agent -s)"
        chmod 600 id_rsa
        ssh-add id_rsa

    - name: Run Ansible Playbook
      run: |
        ls -la
        mkdir ~/.ssh
        cp id_rsa ~/.ssh/
        ssh-keygen -f ~/.ssh/id_rsa -y > ~/.ssh/id_rsa.pub
        ls -la ~/.ssh/
        scp example.php root@172.104.246.224:/tmp/